repos:
-   repo: https://github.com/kynan/nbstripout    
    rev: 0.5.0
    hooks:
    - id: nbstripout
      language_version: python3.8

-   repo: https://github.com/nbQA-dev/nbQA    
    rev: 1.3.1
    hooks:    
    - id: nbqa-black      
      args: [--nbqa-mutate]       

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black


-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort

